# Starter pipeline    
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- master

# TODO: Replace the agent pool name
pool: myAgentPool

variables:
  # TODO: Replace the service connection name
  azureServiceConnectionId: 'myservice207276'
  
  # TODO: Replace 'mywebapp193576' with the existing Web App name
  webAppName: 'mywebapp207276'

  # Environment name
  environmentName: 'flask-ml-service'

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool: myAgentPool
    steps:    
    - script: |
        python3.7 -m pip install --upgrade pip
        python3.7 -m pip install setup
        python3.7 -m pip install -r starter_files/requirements.txt
      workingDirectory: $(projectRoot)

    - script: |
        export PATH=$HOME/.local/bin:$PATH
        make install
        make lint
        echo 'hello world'
      workingDirectory: $(projectRoot)
      displayName: 'Run lint tests'



